---

- name: Wipe App
  when: web_app_full_wipe
  block:
    - name: Check if App directory exists
      ansible.builtin.stat:
        path: '{{ web_app_app_dir }}'
      register: app_dir_stat

    - name: Check if docker-compose.yaml exists
      ansible.builtin.stat:
        path: '{{ web_app_app_dir }}/docker-compose.yaml'
      register: docker_compose_stat

    - name: Docker Compose Down
      when: docker_compose_stat.stat.exists
      changed_when: false
      ansible.builtin.command: docker compose down
      args:
        chdir: '{{ web_app_app_dir }}'

    - name: Remove App directory
      when: app_dir_stat.stat.exists
      changed_when: false
      ansible.builtin.command: rm -rf {{ web_app_app_dir }}

    - name: Remove Docker Images
      changed_when: false
      ansible.builtin.command: docker rmi {{ web_app_image }}
