---
- name: Pull image
  community.docker.docker_image:
    name: "{{ image_name }}"
    source: "pull"
    state: "present"
    tag: "{{ image_tag }}"
  when: not wipe

- name: Manage container
  # Note: runs both on normal run and on wipe
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{image_name}}:{{image_tag}}"
    state: "{{ wipe | ternary('absent', 'started') }}"
    ports: "{{ publish_ports }}"

- name: Wipe image
  community.docker.docker_image:
    name: "{{ image_name }}"
    tag: "{{ image_tag }}"
    state: "absent"
  when: wipe
