---
- name:
  block:
    - name: Create directory
      ansible.builtin.file:
        name: "{{ app_dir }}"
        state: directory

    - name: Deploy compose.yaml
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: "{{ app_dir }}/compose.yaml"

    - name: Start app
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        state: present

- name: Wipe
  import_tasks: 0-wipe.yml
  tags: wipe
  when: wipe == true
