- name: Deploy the app
  block:
    - name: Create folder on machine
      ansible.builtin.file:
        name: "{{ web_app_compose_path }}/"
        state: directory

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: "{{ web_app_compose_path }}/compose.yaml"

    - name: Start web app
      community.docker.docker_compose_v2:
        project_src: "{{ web_app_compose_path }}"
        state: present
  tags: deploy

- name: Wipe webapp
  import_tasks: 0-wipe.yaml
  tags: wipe
  when: web_app_full_wipe == true