---

- name:
  block:
    - name: Create directory for the app
      ansible.builtin.file:
        name: "{{ app_directory }}/"
        state: directory

    - name: Deploy compose.yaml
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: "{{ app_directory }}/compose.yaml"
      vars:
        publish_ports: "{{ exposed_ports }}"
        app_image: "{{docker_image}}:{{tag}}"

    - name: Start the app
      community.docker.docker_compose_v2:
        project_src: "{{ app_directory }}"
        state: present
  tags: docker_compose

- name: Wipe the app
  import_tasks: 0-wipe.yml
  tags: wipe
  when: wipe == true
