---
# Check if nginx is installed

- name: Check if nginx is install on the system
  command: nginx -v
  register: nginx_version
  ignore_errors: true

- name: Install nginx using apt
  apt:
    name: nginx
    state: present
  when: nginx_version.rc != 0
  notify: restart
  tags:
    - setup

- name: Copy nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/{{ app_name }}
  notify: restart
  tags:
    - setup