- name: Delete web_app
  tags:
    - wipe_web_app
  when: wipe_web_app
  block:
    - name: Stop, remove a container {{container_name}}
      docker_container:
        name: "{{ container_name }}"
        state: absent
        keep_volumes: false

