version: "3"

networks:
  loki:

services:
  python_app:
    image: slry/python_moscow_time:latest
    ports:
      - "8081:8080"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"

  typescript_app:
    image: slry/typescript_moscow_time:latest
    ports:
      - "8082:8080"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./promtail.yaml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
