version: "3"

networks:
  loki:

services:
  app_python:
    image: rinri/python-test-app_python
    ports:
      - "8000:8000"
    networks:
      - loki
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}"
        max-size: "200k"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: 500M

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: 500M

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: 500M

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: 500M

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - loki
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: 500M
