version: '3.8'

networks:
  loki:

x-logging: &default-logging
  driver: 'json-file'
  options:
    tag: '{{.ImageName}}|{{.ContainerName}}'
    max-size: '500k'
    max-file: '10'

services:
  app_python:
    image: pptx704/app_python:latest
    ports:
      - 5000:5000
    logging: *default-logging
  
  app_bun:
    image: pptx704/app_bun:latest
    ports:
      - 5001:3000
    logging: *default-logging

  loki:
    image: grafana/loki:latest
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    logging: *default-logging

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    logging: *default-logging
    ports:
      - '9080:9080'

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    ports:
      - '3000:3000'
    logging: *default-logging
