global:
  scrape_interval: 5s

scrape_configs:
- job_name: "loki"
  static_configs:
  - targets: ["loki:3100"]

- job_name: "grafana"
  static_configs:
  - targets: ["grafana:3000"]

- job_name: "promtail"
  static_configs:
  - targets: ["promtail:9080"]

- job_name: "time_web"
  static_configs:
  - targets: ["time_web:5000"]

- job_name: "prometheus"
  static_configs:
  - targets: ["prometheus:9090"]