global:
  scrape_interval: 5s

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - prometheus:9090

- job_name: loki
  static_configs:
    - targets:
        - loki:3100

- job_name: webapp
  static_configs:
    - targets:
        - webapp:80

- job_name: promtail
  static_configs:
    - targets:
        - promtail:9080

- job_name: grafana
  static_configs:
    - targets:
        - grafana:3000