apiVersion: v1
kind: Pod
metadata:
  name: multi-demo
spec:
  volumes:
    - name: workdir
      emptyDir: {}
  initContainers:
    - name: init1
      image: busybox
      command: ["sh", "-c", 'echo "Init 1" > /workdir/test.txt']
      volumeMounts:
        - name: workdir
          mountPath: "/workdir"
    - name: init2
      image: busybox
      command: ["sh", "-c", 'echo "Init 2" >> /workdir/test.txt']
      volumeMounts:
        - name: workdir
          mountPath: "/workdir"
    - name: init3
      image: busybox
      command: ["sh", "-c", 'echo "Init 3" >> /workdir/test.txt']
      volumeMounts:
        - name: workdir
          mountPath: "/workdir"
  containers:
    - name: main
      image: busybox
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: workdir
          mountPath: "/workdir"
