- name: Deploy python app
  hosts: all
  become: true
  roles:
    - role: ../../../roles/web_app
  vars:
    app_dir: app_python
    app_image: metafates/app_python
    app_port: 8000
    web_app_full_wipe: true
