- name: Install web app
  hosts: all
  become: true

  roles:
    - web_app
  vars:
    docker_image: "vladdan16/app_python:latest"
    container_name: "web_app"
    exposed_port: "8000"
    app_dir: "app"
    wipe: false
