---
- name: Install pip
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present
    update_cache: yes

- name: Install Docker Compose
  pip:
    name:
      - docker
      - docker-compose
    state: present
