
---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: "{{ docker_gpg_key }}"
    state: present

- name: Set up the stable repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes

- name: Install Docker Engine
  ansible.builtin.apt:
    name: docker-ce={{ docker_version }}
    state: present
    update_cache: yes
  notify: Restart Docker

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
