---
# Install docker-compose using pip
- name: Install docker sdk
  pip:
    name: docker == 6.1.3
    state: present
  tags: docker
  
- name: Install docker-compose
  pip:
    name: docker-compose
    state: latest
  tags: docker
  notify: start_docker
