---

- name: Install pip
  apt:
    name: python3-pip
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: present
