- name: Upgrade Python3-pip
  apt:
    name: python3-pip
    state: latest
  tags: pip

- name: Upgrade pip
  pip:
    name: pip
    state: latest
  tags: pip

- name: Docker SDK installation
  pip:
    name: docker == 6.1.3
    state: present
  tags: docker

- name: docker-compose installation
  pip:
    name: docker-compose
    state: latest
  tags: docker
  notify: start_docker