- name: Python3 and pip3 installation
  apt:
    name:
      - python3
      - python3-pip

- name: Install docker
  import_tasks: install_docker.yml

- name: Install docker compose
  import_tasks: install_compose.yml