name: app_java

on:
  push:
    paths:
      - app_java/**
      - .github/workflows/app_java.yaml

jobs:
  ensure-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app_java
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
        
  ensure-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args:
            -snyk
            -test app_java --skip-unresolved --severity-threshold=critical

  docker:
    runs-on: ubuntu-latest
    needs: ['ensure-quality']
    defaults:
      run:
        working-directory: ./app_java
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app_python
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/anon_threats:latest
          
