name: Python web application

on: [pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 

      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          pip install -r app_python/requirements.txt
          
      - name: Lint with Ruff
        run: |
          ruff --output-format=github .
        continue-on-error: true

      - name: Test with pytest
        run: |
          cd app_python
          python -m pytest

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: ls
        run: ls
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: app_python
          file: app_python/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/flask-msktime-app:v1