name: Python web application

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 

      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff, pytest
          pip install -r app_python/requirements.txt
          
      - name: Lint with Ruff
        run: |
          ruff --output-format=github .
        continue-on-error: true

      - name: Test with pytest
        run: |
          cd app_python
          python -m pytest