name: Python app

on:
  push:
    paths:
      - 'app_python/**'
      - '.github/workflows/build-python.yaml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
        working-directory: app_python
      
      # Linting using Pylint
      - name: Linter
        run: pylint app_python
      
      # Testing using unittest
      - name: Run tests
        run: python -m unittest app_python/test.py
  
  security:
    runs-on: ubuntu-latest
    needs: build
    if : always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
        working-directory: app_python

      # Download and install Snyk
      - name: Download and install Snyk
        run: |
          curl -LO https://github.com/snyk/cli/releases/download/v1.1278.0/snyk-linux
          chmod +x snyk-linux
        working-directory: app_python 
      
      # Run Snyk
      - name: Run Snyk
        run: ./snyk-linux test --severity-threshold=high
        working-directory: app_python
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: security
    if: ${{ needs.security.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Build and push the image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app_python
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_python:latest