name: Kotlin app

on:
  push:
    paths:
      - 'app_kotlin/**'

defaults:
  run:
    working-directory: app_kotlin

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Lint with Spotless
        run: ./gradlew spotlessApply
        continue-on-error: true

      - name: Test with kotlin.test
        run: ./gradlew test

      - uses: snyk/actions/setup@master

      - name: Snyk test
        run: snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}



  docker:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app_kotlin
          file: app_kotlin/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/moscow-time-app-kotlin:latest