name: Bun app

on:
  push:
    paths:
      - 'app_bun/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11
          
      # Install dependencies
      - name: Install dependencies
        run: cd app_bun && bun install

      # Run tslint
      - name: Run tslint
        run: cd app_bun && bun run tslint -c tslint.json "*.ts"
      
      # Run tests and build
      - name: Run tests
        run: cd app_bun && bun test && bun build ./entry.ts --outdir ./out 

      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Build and push the image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app_bun
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_bun:latest