name: Bun app

on:
  push:
    paths:
      - 'app_bun/**'
      - '.github/workflows/build-bun.yaml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11
          
      # Install dependencies
      - name: Install dependencies
        run: bun install
        working-directory: app_bun

      # Run tslint
      - name: Run tslint
        run: bun run tslint -c tslint.json "*.ts"
        working-directory: app_bun
        continue-on-error: true

      # Run tests and build
      - name: Run tests
        run: bun test && bun build ./entry.ts --outdir ./out 
        working-directory: app_bun 

  security:
    runs-on: ubuntu-latest
    needs: build
    if : ${{ needs.build.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11
      - run: bun install
        working-directory: app_bun

      # Download and install Snyk
      - name: Download and install Snyk
        run: |
          curl -LO https://github.com/snyk/cli/releases/download/v1.1278.0/snyk-linux
          chmod +x snyk-linux
        working-directory: app_bun 
      
      # Run Snyk
      - name: Run Snyk
        run: ./snyk-linux test --severity-threshold=high
        working-directory: app_bun
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: security
    if: ${{ needs.security.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Build and push the image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app_bun
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_bun:latest