name: lint & build docker

on:
  push:
    paths:
      - 'app_python/requirements.txt'
      - 'app_python/app/**'
      - 'app_python/Dockerfile'


jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        working-directory: ./app_python
        with:
          dockerfile: Dockerfile

  build:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        working-directory: ./app_python

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        working-directory: ./app_python

      - name: Set up Docker Hub
        uses: docker/login-action@v3
        working-directory: ./app_python
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and push
        uses: docker/build-and-push-action@v5
        working-directory: ./app_python
        with:
          push: true
          tags: slry/python_moscow_time:latest

