name: Lint

on:
    push:
    pull_request:

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./app_python

        steps:
            -   name: Check code
                uses: actions/checkout@master

            -   name: Setup Python
                uses: actions/setup-python@master
                with:
                    python-version: 3.10.13
                    cache: pip

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                    pip install pytz

            -   name: Lint with pylint
                run: |
                    pip install pylint
                    pylint app.py