name: CI/CD

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Actions chechout
        uses: actions/checkout@v2

      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements
        run: pip install -r app_python/requirements.txt
          
      - name: Install flake8
        run: pip install flake8

      - name: Run flake8 with mccabe analysis
        run: flake8 --max-complexity 10 .

      - name: Run tests
        run: python -m unittest discover -s app_python
        
      - name: Run Snyk
        uses: snyk/actions/python-3.8@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args:
            -test app_python --skip-unresolved

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/lab2:latest "app_python/"
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/lab2:latest