name: CI Workflow

on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app_python/requirements.txt

      - name: Linting
        run: |
          python3 -m flake8

      - name: Tests
        run: |
          python3 -m unittest discover -s app_python/src/tests -p "test_application.py"