name: Python CI

on:
  push:
    paths:
      - 'app_python/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Python dependencies cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('app_python/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r app_python/requirements.txt

    # - name: Change file directory
    #   run: cd app_python/

    - name: Lint code
      run: flake8 app_python

    - name: Run tests
      run: pytest
  
  security:
    runs-on: ubuntu-latest

    needs:
      - build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.10@master
        with:
          args: --skip-unresolved app_python/
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
  docker:
    runs-on: ubuntu-latest

    needs:
      - build
    services:
      docker:
        image: docker:latest
        options: --privileged
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app_python:latest ./app_python
          docker push ${{ secrets.DOCKER_USERNAME }}/app_python:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}