name: Snyk Security Check

on:
    push:
    pull_request:

permissions:
    contents: read

jobs:
    snyk-check:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@master

            -   name: Cache dependencies
                uses: actions/cache@master
                with:
                    path: ~/.cache/pip
                    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                    restore-keys: |
                      ${{ runner.os }}-pip-

            -   name: Setup Python
                uses: actions/setup-python@master
                with:
                    python-version: 3.10.13
                    cache: pip

            -   name: Install dependencies
                run: pip install -r app_python/requirements.txt

            -   name: Install Snyk CLI
                run: npm install -g snyk

            -   name: Authenticate Snyk
                run: snyk auth ${{ secrets.SNYK_TOKEN }}

            -   name: Setup Snyk
                uses: snyk/actions/setup@master
