name: Snyk Security Check

on:
    push:
    pull_request:

permissions:
    contents: read

jobs:
    snyk-check:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@master

            -   name: Snyk Security Check
                uses: snyk/actions/python-3.10@master
                with:
                    args: --file=app_python/requirements.txt --package-manager=pip
                env:
                    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
