name: Test

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main


jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup Python
                uses: actions/setup-python@v5
                with:
                    python-version: 3.10.13

            -   name: Install dependencies
                run: pip install -r requirements.txt

            -   name: Test
                run: python -m unittest
