name: Test

on:
    push:
    pull_request:

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@master

            -   name: Setup Python
                uses: actions/setup-python@master
                with:
                    python-version: 3.10.13
                    cache: pip

            -   name: Install dependencies
                run: pip install -r app_python/requirements.txt

            -   name: Test
                run: python -m unittest